let car = 'subaru';
let age = 25;
let fruits1 = ['apple', 'banana', 'orange'];
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Is car == 'audi'? I predict False.");
console.log(car == 'audi');
console.log("Is car.toLowerCase() == 'SUBARU'? I predict False.");
console.log(car.toLowerCase() == 'SUBARU'); 
console.log("Is car.toLowerCase() == 'subaru'? I predict True.");
console.log(car.toLowerCase() == 'subaru'); 
console.log("Is age >= 25? I predict True.");
console.log(age >= 25);
console.log("Is age > 30? I predict False.");
console.log(age > 30);
console.log("Is age >= 25 && car == 'subaru'? I predict True.");
console.log(age >= 25 && car == 'subaru');
console.log("Is age < 20 || car == 'audi'? I predict False.");
console.log(age < 20 || car == 'audi');
console.log("Is 'banana' in fruits? I predict True.");
console.log('banana' in fruits1);
console.log("Is 'mango' in fruits? I predict False.");
console.log('mango' in fruits1);
